language: php

php:
 - 5.6
 - 7.0
 - 7.1
 - 7.2
 - hhvm

fast_finish: true

bin-dir: vendor/bin/

allow_failures:
  - php: hhvm

before_script:
- composer install -o -n

script:
  - vendor/bin/phpunit --testdox --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
